### ISSUE TITLE
formatting codes don't work in the console

### ISSUE THREAD

**Issue by holli2801** [WiIIiam278/HuskChat#106]
formatting codes set in config.yml don't get set in console. 

![image](https://user-images.githubusercontent.com/68467070/222894618-823d13b6-23ec-4d41-b6b7-11c65bd701e1.png)

I thought it might be a console issue. but other plugins work fine and apply the formatting codes set in their configs.

**Comment by WiIIiam278** [comment]
seems like the message is being spat through the logger and not the adventure console audience. Odd.
