### ISSUE TITLE
[Feature Request] Global Join and Leave messages

### ISSUE THREAD

**Issue by holli2801** [WiIIiam278/HuskChat#107]
Currently, join and leave messages are displayed in chat whenever someone moves servers inbetween the network. 

Since HuskChat creates a global chat, if someone moves to another server of the network, it looks like they are leaving the network. 

It would be very useful to have a global join and leave message for when someone joins and leaves the whole network. 
This message could be customized in the config.yml.

**Comment by holli2801** [comment]
you could also add messages for when players move to a different server in the network. Something like:
"Player teleported to [server name]"

**Comment by Ashurit** [comment]
I would be glad to see this feature implemented, avoiding to require a separated plugin to manage it and have a fully integrated solution with the current chat system through HuskChat 🤩
