### ISSUE TITLE
[Feature Request] discord support (via spicord)

### ISSUE THREAD

**Issue by gadget78** [WiIIiam278/HuskChat#127]
adding discord-->minecraft(huskchat) support would be great,
i think the easiest solution would be to use Spicord 
found here  --> https://www.spigotmc.org/resources/spicord.64918/
or on github here --> https://github.com/Spicord/Spicord
as this mod can take care off all the discord configuration, and gives out a API that can used within huskchat

this mod can be solely put on velocity...

if possible, can we name what servers the discord chat goes to, 
and maybe options to listen to bots that post in discord ?

**Comment by NullOrNaN** [comment]
I would love to see this as well. I'm not familiar with the code base so sadly, I'll likely be no help by submitting a PR. If there's anything I can do including testing please let me know!
