### ISSUE TITLE
[FEAT Request] Add format by group

### ISSUE THREAD

**Issue by SwartZCoding** [WiIIiam278/HuskChat#128]
All in the title, add posibility to change chat format by group.

**Comment by WiIIiam278** [comment]
you uhh.. can?

**Comment by SwartZCoding** [comment]
> you uhh.. can?

Didn't see anything on the config & the doc to do something like that ?

**Comment by WiIIiam278** [comment]
It's the section labelled "format" \:)

https://github.com/WiIIiam278/HuskChat/blob/b8020533031c2e306081174485a93022d15ee683/common/src/main/resources/config.yml#L21-L23

**Comment by SwartZCoding** [comment]
> 

I talk about define specific format by a luckperm group. Here it's the same for all groups

**Comment by WiIIiam278** [comment]
You can — use the %prefix%, %suffix% and %groupname% placeholders and embed color codes

**Comment by SwartZCoding** [comment]
> You can — use the %prefix%, %suffix% and %groupname% placeholders and embed color codes

is not very easiest way if we need to custom lots of things by group.

Maybe add a category like this can be a cool thing : 
format-by-group: 
  rank1: "your formating"
  rank2: "your formating"
  rank3: "your formating"
  rank4: "your formating"

**Comment by WiIIiam278** [comment]
I prefer group customisation be done entirely in LuckPerms itself using its set of meta keys and not in individual plugin configs, so gonna close this out for now.
