### ISSUE TITLE
More options for huskchat

### ISSUE THREAD

**Issue by Kasviss** [WiIIiam278/HuskChat#130]
can you add a setting to define a server that uses "normal" chat because I have plugins that use "normal" minecraft chat and they don't work now. or something that fixes this issue.

Example with quickshop: 
![image](https://github.com/WiIIiam278/HuskChat/assets/139772321/12c23c62-126f-4e19-bde0-8f5af9dbb12d)
when I put chat message: "1" it doesn't do anything

(I already asked that for quickshop authors about it and they said this:
> please contact its author, we just handle and cancel chat event currently, nothing wrong in our side)

**Comment by Kasviss** [comment]
Link for quickshop authors reply: https://github.com/PotatoCraft-Studio/QuickShop-Reremake/discussions/383#discussion-5410969

**Comment by WiIIiam278** [comment]
HuskChat is a proxy plugin and won't work with backend plugins by default.

Relevant documentation, which explains why this is the case, and provides examples of how you can work around this: https://william278.net/docs/huskchat/backend-chat-entry
