### ISSUE TITLE
Spicord Integration Bugs

### ISSUE THREAD

**Issue by Aiidoneus** [WiIIiam278/HuskChat#140]
Not sure if you want multiple or all under 1 issue but here is a couple of things I ran into setting everything up. 

Environment:
- Velocity: velocity-3.2.0-SNAPSHOT-265.jar
- Huskchat version: HuskChat-2.6.2.jar

Issue 1:
When running the `/huskchat reload` command, the bot will start duplicating the messages. If you run it once, it will it will send 2 messages. If you run the command again, it will send 3. So on and so forth. Noticed mostly when you sent the messages from Discord to in-game chat. 

Issue 2:
Not 100% sure this is an issue but maybe this is intended but I will try to explain. I have multiple channels setup for multiple servers with the `broadcast_scope` of `LOCAL`. When this is set, the Discord -> Minecraft bridge/bot doesn't send the message. As soon as I turn the scope to `GLOBAL` everything works again. When on LOCAL, messages do get sent from in-game to Discord just not the other way around. 

Hopefully I explained this well enough. If you need more information or need help testing things, let me know!

Thanks in advance, 
Aidoneus

**Comment by WiIIiam278** [comment]
1. Yeah that’s a bug as the logic to initialise this is in the loadconfig stuff. Should prob fix that
2. Well—the spicord bot isn’t on any server, so sending to a local channel wouldn’t really make sense, no? You’d have a situation where the bot could send/receive globally but players couldn’t, kind of defeating the point of having a global channel. Perhaps this should be more clear in the docs.
