### ISSUE TITLE
LiteBans Mute don't work

### ISSUE THREAD

**Issue by ilgrandeanonimo** [WiIIiam278/HuskChat#161]
When i mute somebody with LiteBans he can write and ignore mute

**Comment by ilgrandeanonimo** [comment]
Yes

**Comment by WiIIiam278** [comment]
I don't own a copy of Litebans and it's source code isn't public so I'm unable to investigate further. Contact Litebans support and ask them what `PostOrder` their `PlayerChatEvent` listener is; specifically, if it runs later than `LATE` HuskChat won't be able to catch it.

**Comment by WiIIiam278** [comment]
Closing this as it's blocked by a neccessary follow up with a closed source piece of software
