### ISSUE TITLE
[Feature Request] Add Bypass Permission for Join/Quit Messages

### ISSUE THREAD

**Issue by viasnake** [WiIIiam278/HuskChat#182]
Add an option to suppress messages when a player join or quit.
Specifically, players with a certain permission should be able to hide Join or Quit messages.
Example Permissions: `huskchat.bypass_join_message`, `huskchat.bypass_quit_message`

Some players, like server staff, may prefer not to have their Join or Quit activities revealed. Considering this, having this permission seems beneficial.

Additionally, if there's room for further enhancement, an idea is to introduce a feature allowing the display of Join and Quit messages at any time using commands.

**Comment by WiIIiam278** [comment]
Already added in https://github.com/WiIIiam278/HuskChat/pull/175
