### ISSUE TITLE
Chat disabled due to missing profile public key. Please try reconnecting.

### ISSUE THREAD

**Issue by KjellDE** [WiIIiam278/HuskChat#195]
Sending a chat message will result in the following error:
```console
[12:16:04 WARN]: Failed to update secure chat state for <user>: 'Chat disabled due to missing profile public key. Please try reconnecting.'
```

However, using `/g <message>`, `/l <message>`, etc. will not result in this error.

**Comment by KjellDE** [comment]
I've followed the documentation and SignedVelocity is already installed.

**Comment by WiIIiam278** [comment]
Disable `enforce-secure-profile` on all backends

**Comment by WiIIiam278** [comment]
Made redundant by #196
