### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by BunkDev5674** [WiIIiam278/HuskChat#2]
broken no work bcuz bad

**Comment by WiIIiam278** [comment]
Please describe your issue in detail rather than saying "plugin bad". Remember this is a bungee plugin to be installed on your proxy server.

**Comment by BunkDev5674** [comment]
how else to explain, its jsut no work

**Comment by BunkDev5674** [comment]
and me not dumb dumb i alr know its bungee smh

**Comment by WiIIiam278** [comment]
Could you post your startup logs and config file?

**Comment by WiIIiam278** [comment]
Closing as invalid
