### ISSUE TITLE
[Feature Request]: Supports JSON format

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskChat#230]
[Feature Request]: Supports JSON format

**Comment by WiIIiam278** [comment]
What for? I don't quite know what you're asking for :)

**Comment by MSCMDD** [comment]
EmmmmMake JSON text available for output to the chat box

**Comment by WiIIiam278** [comment]
We support MineDown; support for Adventure MiniMessage is planned for the future.
