### ISSUE TITLE
[BUG] The color code of the PAPI variable is missing

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskChat#235]
The color code of the PAPI variable is missing

When I use PAPI to output %essentials_nickname% it has color, but when I add it to HuskChat the color is lost

Maybe we can make the PAPI variable color optional or not

**Comment by MSCMDD** [comment]
![image](https://github.com/WiIIiam278/HuskChat/assets/128666602/138b96ce-6f0c-44d2-8fd5-4b5c931c4652)

**Comment by MSCMDD** [comment]
![image](https://github.com/WiIIiam278/HuskChat/assets/128666602/869e1e83-5c3d-40c8-8888-8a4e94efc9a2)

**Comment by MSCMDD** [comment]
![image](https://github.com/WiIIiam278/HuskChat/assets/128666602/95cc74ac-6f9c-4a0b-9fe2-2323046568a6)

**Comment by WiIIiam278** [comment]
Placeholders with legacy color codes aren't fully supported as MineDown is used for formatting
