### ISSUE TITLE
Chat Messages Not Being Readable to Other Plugins

### ISSUE THREAD

**Issue by SuperZekes** [WiIIiam278/HuskChat#248]
I have quickshops plugin installed on one of my servers and as an example if I click on the sign it will ask me "Enter in chat how many you wish to buy" and I would enter "2" it did not work! I then tried removing HuskChat and that fixed the issue.

**Comment by WiIIiam278** [comment]
https://william278.net/docs/huskchat/backend-chat-entry

**Comment by WiIIiam278** [comment]
This is working as intended
