### ISSUE TITLE
Folia Error Scheduler

### ISSUE THREAD

**Issue by Euphillya** [WiIIiam278/HuskChat#252]
https://github.com/WiIIiam278/HuskChat/blob/2999358a0136779451f18218afa58c8d1aa21a6f/bukkit/src/main/java/net/william278/huskchat/event/BukkitEventProvider.java#L37

https://github.com/WiIIiam278/HuskChat/blob/2999358a0136779451f18218afa58c8d1aa21a6f/bukkit/src/main/java/net/william278/huskchat/event/BukkitEventProvider.java#L50

Schedulers are not functional on Folia, because it uses those from bukkit.

**Comment by WiIIiam278** [comment]
Duplicate of #226

**Comment by Euphillya** [comment]
Duplicate but not fixed
