### ISSUE TITLE
Social spies see their own private messages twice

### ISSUE THREAD

**Issue by t4gh5yj6j** [WiIIiam278/HuskChat#29]
![image](https://user-images.githubusercontent.com/67204462/161111368-714c26f7-63eb-41a0-bfae-b3b3c6f485ed.png)

make private messages sent by people with specific permission not to be sent in socialspy

**Comment by WiIIiam278** [comment]
Closed in https://github.com/WiIIiam278/HuskChat/commit/4fe6485c528d39b360bdec68cf46eee88406ed3e
