### ISSUE TITLE
GroupManager permission plugin support

### ISSUE THREAD

**Issue by jwpwnz** [WiIIiam278/HuskChat#31]
Great plugin but Is it possible to make this work with GroupManager? Not a fan of lucky perms a lot of people still use groupmanager I was told to post about this here.

**Comment by WiIIiam278** [comment]
Not currently a feature but can be I guess. I sort of assume luckperms is a standard everyone uses these days though tbh

**Comment by WiIIiam278** [comment]
I looked into this - but HuskChat is a proxy plugin and GroupManager is spigot only. Sorry.
