### ISSUE TITLE
Demoted players can still see Spy

### ISSUE THREAD

**Issue by TrainerMoon** [WiIIiam278/HuskChat#37]
Hi I was demoted from a moderator on a server that uses this plugin but I can still see other people's whispers.

**Comment by Iotados** [comment]
Assumption on cause: the toggle does not have a check for the permission node when it is toggled on

**Comment by Iotados** [comment]
actually hold on, the toggle doesn't even exist yet for any public versions... this would appear to be cause by else. 

Will investigate the cause of this

**Comment by TrueWinter** [comment]
The command to toggle socialspy does have a [permission check](https://github.com/WiIIiam278/HuskChat/blob/master/common/src/main/java/net/william278/huskchat/command/SocialSpyCommand.java#L29), but the permission isn't checked before [sending the socialspy message](https://github.com/WiIIiam278/HuskChat/blob/master/common/src/main/java/net/william278/huskchat/message/PrivateMessage.java#L52).

**Comment by WiIIiam278** [comment]
> The command to toggle socialspy does have a [permission check](https://github.com/WiIIiam278/HuskChat/blob/master/common/src/main/java/net/william278/huskchat/command/SocialSpyCommand.java#L29), but the permission isn't checked before [sending the socialspy message](https://github.com/WiIIiam278/HuskChat/blob/master/common/src/main/java/net/william278/huskchat/message/PrivateMessage.java#L52).

Yeah, the fix for this would be as simple as installing a permission check there and if it fails remove them from the spy list

**Comment by WiIIiam278** [comment]
Fixed in #38
