### ISSUE TITLE
Allow filters to be used on private messages and allow fine-tuning of which filters to use for them and per-channel

### ISSUE THREAD

**Issue by xF3d33** [WiIIiam278/HuskChat#40]
normally you can't spam messages but it /tell you can

**Comment by WiIIiam278** [comment]
Gonna need more details than that -- by /tell do you mean minecraft:tell or huskchat's /msg command ?

**Comment by xF3d33** [comment]
the huskchat command of course. just /tell or /msg

**Comment by WiIIiam278** [comment]
Is the `/huskchat` command also prone to being spammed?
HuskChat offers no builtin command-spam prevention, duly note. Only chat messages.

**Comment by 65-7a** [comment]
By the huskchat command I think they mean huskchat's /msg command.

**Comment by WiIIiam278** [comment]
> By the huskchat command I think they mean huskchat's /msg command.

Using filters on private messages currently isn't a feature, but it seems reasonable enough to want to add this - though it'd probably require adding more options for fine tuning filters on a per-channel basis, too.

@xF3d33 Is this what you're asking for?

**Comment by xF3d33** [comment]
yes

**Comment by xF3d33** [comment]
I thought you forgot or that it was a code error.
