### ISSUE TITLE
Buggy tab complete for group messages

### ISSUE THREAD

**Issue by TrueWinter** [WiIIiam278/HuskChat#45]
If sending a message to multiple people whose names start with the same letters (and case), the tab completion cuts off the first person's name.

https://user-images.githubusercontent.com/30316407/164911342-c155c8d6-c4a7-45a1-8068-9c05cc10ce53.mp4

**Comment by Iotados** [comment]
Does this effect the message being sent the other account?

**Comment by TrueWinter** [comment]
Yeah, the person whose name gets cut off in the tab complete won't receive the message.
