### ISSUE TITLE
Plugin fails to load on latest Velocity

### ISSUE THREAD

**Issue by twiceineverymoment** [WiIIiam278/HuskChat#56]
Using the latest build of Velocity (3.1.2 build 153) the plugin throws an error during startup. Global chat does not appear to work at all.

`[18:11:40 ERROR]: Couldn't pass ProxyInitializeEvent to huskchat
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null
	at net.william278.huskchat.config.Settings.fetchChatFilters(Settings.java:267) ~[?:?]
	at net.william278.huskchat.config.Settings.load(Settings.java:121) ~[?:?]
	at net.william278.huskchat.velocity.HuskChatVelocity.reloadSettings(HuskChatVelocity.java:162) ~[?:?]
	at net.william278.huskchat.velocity.HuskChatVelocity.onProxyInitialization(HuskChatVelocity.java:93) ~[?:?]
	at net.william278.huskchat.velocity.Lmbda$6.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Comment by TrueWinter** [comment]
Could you please share your config?

This appears to be an issue related to my last pull request (#54). If it is, the config will verify this assumption and I can submit a new pull request to better handle the config loading.

**Comment by twiceineverymoment** [comment]
This is what we have currently, which is working. We determined that attempting to remove 'helpop' channel is what was causing the failure. We were hoping to remove that as we already have another plugin handling that command.

`#  ------------------------------
# |        HuskChat Config      |
# |    Developed by William278  |
#  ------------------------------
# Configuration guide: https://github.com/WiIIiam278/HuskChat/wiki
# To modify individual message locales, see the messages file.

# General options. Default channel should match one of the channels below.
language: en-gb
default_channel: local
channel_log_format: '[%servername%|%channel%] %sender%: '
# Must contain at least one item; the first being the primary alias of the command
channel_command_aliases:
- /channel
- /c

# Chat channel configuration.
# - You can edit the default channels and make your own if you would like.
# - Channels that have permissions set require them to send and receive messages respectively.
channels:
  local:
    format: ''
    broadcast_scope: PASSTHROUGH
    log_to_console: true
    shortcut_commands:
    - /local
    - /l
  global:
    format: '&#00fb9a&▮ %fullname%&r&f: '
    broadcast_scope: GLOBAL_PASSTHROUGH
    log_to_console: true
    shortcut_commands:
    - /global
    - /g
  #restricted_servers: # Set where it is not possible to use this channel
  #  - minigame
  staff:
    format: '&6[S]&r&f%prefix% &6%name%: &7'
    broadcast_scope: GLOBAL
    log_to_console: true
    filtered: false
    permissions:
      send: huskchat.channel.staff.send
      receive: huskchat.channel.staff.receive
    shortcut_commands:
    - /staff
    - /sc
  helpop:
    format: '&#00fb9a&[HelpOp] %name%: &7'
    broadcast_scope: GLOBAL
    log_to_console: true
    filtered: false
    permissions:
      receive: huskchat.channel.helpop.receive
    shortcut_commands:
    - /helpop
    - /helpme

# Server Default Channel Configuration
# - Set a channel that the player will automatically be set to when changing servers
# - Players will still be able to switch channels and use /msg and /r unless you add servers to the restricted_servers list
#server_default_channels:
#  minigame: local

# Options for the /msg and /r commands
message_command:
  enabled: false
  msg_aliases:
  - /msg
  - /m
  - /tell
  - /whisper
  - /w
  - /pm
  reply_aliases:
  - /reply
  - /r
  log_to_console: true
  log_format: '[MSG] [%sender% -> %receiver%]: '
  # Whether to allow sending and replying to a message in a group (/msg User1,User2 <message>)
  # Whether to allow sending and replying to a message in a group (/msg User1,User2 <message>)
  group_messages:
    enabled: true
    max_size: 5
  # Formats for the /msg command (MineDown syntax). A separate format is used for group private messages.
  # Formats for the /msg command (MineDown syntax). A separate format is used for group private messages.
  format:
    inbound: '&#00fb9a&%name% &8→ &#00fb9a&You&8: &f'
    outbound: '&#00fb9a&You &8→ &#00fb9a&%name%&8: &f'
    group_inbound: '&#00fb9a&%name% &8→ &#00fb9a&You [₍₊%group_amount_subscript%₎](gray show_text=&7%group_members% suggest_command=/msg %group_members_comma_separated% )&8: &f'
    group_outbound: '&#00fb9a&You &8→ &#00fb9a&%name% [₍₊%group_amount_subscript%₎](gray show_text=&7%group_members% suggest_command=/msg %group_members_comma_separated% )&8: &f'
#restricted_servers: # Set where /msg and /r cannot be used
#  - hub

# Options for the /socialspy command
social_spy:
  enabled: false
  format: '&e[Spy] &7%sender_name% &8→ &7%receiver_name%:%spy_color% '
  group_format: '&e[Spy] &7%sender_name% &8→ &7%receiver_name% [₍₊%group_amount_subscript%₎](gray show_text=&7%group_members% suggest_command=/msg %group_members_comma_separated% ):%spy_color% '
  socialspy_aliases:
  - /socialspy
  - /ss
# Options for the /localspy command
local_spy:
  enabled: true
  format: '&e[Spy] &7[%channel%] %name%&8:%spy_color% '
  localspy_aliases:
  - /localspy
  - /ls
#excluded_local_channels: # Channels to exclude from local spying
#  - local
# Options for the /broadcast command
broadcast_command:
  enabled: true
  broadcast_aliases:
  - /broadcast
  - /alert
  format: '&e&l[!]&e '
  log_to_console: true
  log_format: '[BROADCAST]: '

# Chat filter options
chat_filters:
  # Filters against IP addresses and links
  advertising_filter:
    enabled: false
    private_messages: false
    channels:
    - global
    - local
  # Filters against CAPS use; specify the maximum % a message can contain capital letters
  caps_filter:
    enabled: false
    max_caps_percentage: 0.4
    private_messages: false
    channels:
    - global
    - local
  # Filters against users sending messages too quickly (configure how many messages users can send over a period of seconds)
  spam_filter:
    enabled: false
    period_seconds: 4
    messages_per_period: 3
    private_messages: false
    channels:
    - global
    - local
  # Filters against profanity using machine learning. Requires Python 3.8+ on the server with jep and alt-profanity-check installed.
  profanity_filter:
    enabled: false
    # Define a directory path for the jep library
    library_path: ''
    # Filter rule - AUTOMATIC or TOLERANCE.
    mode: AUTOMATIC
    # If using TOLERANCE mode, the algorithm will determine a profanity probability and compare with this to filter.
    tolerance: 0.78
    private_messages: false
    channels:
    - global
    - local
  repeat_filter:
    enabled: true
    previous_messages_to_check: 2
    private_messages: false
    channels:
    - global
    - local
  # Filters against the use of non-ASCII (Unicode) characters
  ascii_filter:
    enabled: false
    private_messages: false
    channels:
    - global
    - local

# Chat message replacer options
message_replacers:
  # Replaces text emoticons in messages with the correct emoji
  emoji_replacer:
    enabled: true
    case_insensitive: false
    private_messages: true
    channels:
    - global
    - local
    - helpop
    - staff
    # Emote character options: https://gist.githubusercontent.com/WiIIiam278/b74a6af6d9670350a60ad09d63b67169/raw/d8b596471c812eb2b68638469cb779d928bd733f/minecraft_unicode_characters.txt
    # Emote character options: https://gist.githubusercontent.com/WiIIiam278/b74a6af6d9670350a60ad09d63b67169/raw/d8b596471c812eb2b68638469cb779d928bd733f/minecraft_unicode_characters.txt
    emoji:
      :): ☺
      ':smile:': ☺
      :-): ☺
      :(: ☹
      ':frown:': ☹
      :-(: ☹
      ':fire:': 🔥

# Version of the config file
config-version: 1`

**Comment by twiceineverymoment** [comment]
(moved to pastebin since github didn't format it correctly):

https://pastebin.com/4uRuZCNg

This version is working. We determined that attempting to remove the 'helpop' channel was the cause of the crash; we already have another plugin handling that command so were hoping to remove it.

**Comment by TrueWinter** [comment]
Yeah, that definitely confirms the idea I had about the cause of the error. If you remove a channel, you will need to ensure that no message filters (or the emoji replacer) reference the removed channel.

So if you want to remove the `helpop` channel, you'll also need to remove it at line 186 in the config.

I'll submit a pull request tomorrow that verifies that channels exist while loading filters.
