### ISSUE TITLE
[feature request] Improve message replacers

### ISSUE THREAD

**Issue by dazogga** [WiIIiam278/HuskChat#62]
Chat message replacer options currently seem to support single characters only. This works great for using basic emojis like `:skull:` for :skull: 
It would be great if longer replacements were available, so a `:tableflip:` could be done resulting in `(╯°□°）╯︵ ┻━┻` or a `:shrug:` for `¯\_(ツ)_/¯`

I would be very glad if you implemented this function, as a functional chat plugin is my last step in migrating to velocity, and I would be very happy to choose HuskChat as my option.

**Comment by WiIIiam278** [comment]
Hi there - the current implementation should already support this. Have you tried doing this?

**Comment by dazogga** [comment]
Well, i tried again and it worked. Sorry for bugging you ;)
First time i tired adding these, i could no longer post any emote. I removed those listings and it worked. Probably just had a syntax mistake somewhere...

But thanks again for the very quick answer!
