### ISSUE TITLE
Velocity kicking players ("A plugin tried to cancel a signed chat message" / "A proxy plugin caused an illegal protocol state")

### ISSUE THREAD

**Issue by gp-Airee** [WiIIiam278/HuskChat#72]
> A plugin tried to cancel a signed chat message. This is no longer possible in 1.19.1 and newer. Disconnecting player ...

Running Velocity 3.1.2-SNAPSHOT (git-1a3fba42-b163) & HuskChat 2.3

**Comment by WiIIiam278** [comment]
Caused by a breaking Velocity API change that HuskChat relies on...

**Comment by WiIIiam278** [comment]
Update: Enquired with the Velocity team, they're working on the API still and this will be resolved soonish :-) I'll leave this open until then!

**Comment by WiIIiam278** [comment]
I have updated this post https://github.com/WiIIiam278/HuskChat/issues/72#issuecomment-1200896060 with more details and a FAQ.

**Comment by LuluxClient** [comment]
Hey any updates reguarding that ?

**Comment by WiIIiam278** [comment]
> Hey any updates reguarding that ?

Nope. When Velocity adds their chat API, things can move. Waiting on them :)

**Comment by WiIIiam278** [comment]
> Is there a workaround with like using a older Velocity Version?

Nope. This is a Velocity issue; they haven't implemented a chat API yet as they want to do so with full respect and support to Mojang's chat signing- that's their decision as explained in the FAQ and so no versions of velocity support cancelling signed chat that work with 1.19.2 currently.

**Comment by voruti** [comment]
I just did something without canceling any messages: https://github.com/voruti/CopyChat/blob/main/src/main/java/voruti/copychat/CopyChat.java#L43.
That's all I need for now; I'll come back to HuskChat later.

**Comment by WiIIiam278** [comment]
@voruti That's neat! Only issue of course is that you can't format the (at least, locally received) messages, or do channel switching, etc.

**Comment by ShackInTheMiddle** [comment]
any update?

**Comment by WiIIiam278** [comment]
Read the OP. There's mitigation instructions there.

**Comment by WiIIiam278** [comment]
HuskChat 2.5 will depend on UnsignedVelocity & VPacketEvents on Velocity going forward.
