### ISSUE TITLE
[Feature Request] Custom server name

### ISSUE THREAD

**Issue by InoryS** [WiIIiam278/HuskChat#82]
Your plugin is great!
No need to install on the server to use, this solved my fabric server chat problem.
I'm wondering if it's possible to customize the server name further, in Multichat I customized the shorter server name, which looks great.
But it seems that only %servername% can be used in HuskChat, is it possible to customize the server name,thanks a lot.

**Comment by WiIIiam278** [comment]
It's not currently really, it goes by what the name is as defined by your proxy. I guess I could add some way of adjusting the capitalisation? But substituting it for something else seems kinda hard to implement in a logical manner. One thing you could do is use luckperms and apply a different prefix through a contextual permission node based on the server the user is on (look up luckperms contexts for how to do this)
