### ISSUE TITLE
maybe chat reports

### ISSUE THREAD

**Issue by klaksik** [WiIIiam278/HuskChat#90]
![image](https://user-images.githubusercontent.com/89664351/206998098-278c61a9-203e-4c0f-a55a-407ec2e9f451.png)
![image](https://user-images.githubusercontent.com/89664351/206998173-4be0998f-4220-4c64-a159-2307f91eb865.png)

**Comment by WiIIiam278** [comment]
Velocity issue. Closing. See pinned issue for details
