### ISSUE TITLE
[Feature request] add RedisBungee support

### ISSUE THREAD

**Issue by Illusionika** [WiIIiam278/HuskChat#91]
Now RedisBungee already supports Velocity (RedisBungee-Velocity), but now any cross-proxy chat plugin that supports redis is based on BungeeCord or Bukkit

HuskChat supports Velocity, can you add redis function to realize chat with multiple proxy instances?

player-info-forwarding-mode = "modern" in Velocity configuration

**Comment by WiIIiam278** [comment]
I suggest using RedisChat instead if you're rocking Redis as I think this is out of scope for my plugin
